hw3
belikoooova/telegram-notifications-bot pull request #4
Opened 2024-02-29 22:17 UTC by belikoooova

2024-03-02 20:42 UTC, belikoooova commented
Есть у меня с друзьями понятие "_ремонт_" при написании кода. Это когда спустя пару дней/при появлении новых знаний смотришь на написанный тобою код, и думаешь: блин, а ведь можно сделать архитектуру грамотнее и чище, после чего возникает навязчивая мысль переделать все с чистого листа)

Я уже один раз провернула это с 1 домашкой, но, кажется, хочу снова... 

Во-первых, в модулях появились http-клиенты, и не совсем понятно: а нужно ли теперь в модуле бота каким-то образом напрямую обращаться к БД? кажется, что все существующие команды бота теперь можно провернуть через клиента, который обращается к апи скрэппера. КРОМЕ моего чат-стейта, который, как выяснилось, все же необходим. Мне стоит: 
    a) Расширить апи скэппера, чтобы он еще и отслеживал и позволял изменять состояние чата (ожидает ли он отправки ссылки или нет)
    b) Все-таки оставить репозиторий в боте, при этом он будет ссылаться на ту же таблицу с чатами, что и скрэппер. Но в боте отслеживать чат-стейт и изменять только его, остальные манипуляции с БД проводить через клиента скрэппера
    
Во-вторых, в вузе сегодня рассказывали, в частности, про прелести DTO: что работа с моделями "сразу из БД" сильно связывает нам руки (может, внутри приложения нам нужно какое-то поле, которое не нужно сохранять в БД) (или если оно не нужно сейчас, потом будет тяжело это править). Формулировка, была, конечно не такая, но я поняла это так. Вот и подумала: может, тут тоже сделать ДТО для сущностей чата и ссылки, и перемапливать их каждый раз из БД?

Очень нужен Ваш совет по поводу всего... Вообще, это мой первый проект такого объема, и складывается почти закономерность, что понимаю, что написала какие-то вещи не очень хорошо только в течение следующих шагов (домашек). Это ведь база?

А еще спросила у препода насчет интерфейсов с одной реализацией, и он ответил, что упрощает процесс тестирования (include мокирования). Вы с этим не согласны?

С благодарностью и надеждой на развернутый ответ❤️

2024-03-02 20:47 UTC, belikoooova commented
Ой, да, и почему, собственно, ремонт:
_Ремонт нельзя закончить, его можно только приостановить_

2024-03-04 19:17 UTC, SHvatov commented
> Ой, да, и почему, собственно, ремонт: _Ремонт нельзя закончить, его можно только приостановить_

~~эх, только в курсе по Java мне ремонта не хватало...~~

2024-03-04 19:23 UTC, SHvatov commented
> Есть у меня с друзьями понятие "ремонт" при написании кода. Это когда спустя пару дней/при появлении новых знаний смотришь на написанный тобою код, и думаешь: блин, а ведь можно сделать архитектуру грамотнее и чище, после чего возникает навязчивая мысль переделать все с чистого листа)

Это замечательно, и, можно сказать, happens all the time) На будущее советую ознакомиться с трудами Роберта Мартина (Чистый код, Чистая архитектура - он тот еще чистюля), а также советую почитать Фаулера - Рефакторинг. Книги, конечно, немного холиварные, но для начала пойдет. 

В идеале такой рефакторинг стоит проводить отдельно от реализации бизнес-логики - гораздо легче понять, что поменялось и на что стоит смотреть. А так просто скоуп расширяется, и за всем ревьюверу уследить становится сложно. Вообще идеально, когда это серия мелких МРов с описанием что изменилось и зачем.

2024-03-04 19:43 UTC, SHvatov commented
> Во-первых, в модулях появились http-клиенты, и не совсем понятно: а нужно ли теперь в модуле бота каким-то образом напрямую обращаться к БД? кажется, что все существующие команды бота теперь можно провернуть через клиента, который обращается к апи скрэппера. КРОМЕ моего чат-стейта, который, как выяснилось, все же необходим. Мне стоит:
a) Расширить апи скэппера, чтобы он еще и отслеживал и позволял изменять состояние чата (ожидает ли он отправки ссылки или нет)
b) Все-таки оставить репозиторий в боте, при этом он будет ссылаться на ту же таблицу с чатами, что и скрэппер. Но в боте отслеживать чат-стейт и изменять только его, остальные манипуляции с БД проводить через клиента скрэппера

Есть золотое правило - один сервис, одна БД. Далее я предлагаю тебе подумать, какие сущности к какому из сервисов относятся. При этом хочу обратить твое внимание на то, что в микросервисной архитектуре нормально, когда код дублируется (в том числе и таблицы). К примеру, можно попробовать следующим образом:

![image](https://github.com/belikoooova/telegram-notifications-bot/assets/15994914/09423488-a663-4fab-9d0d-5755f93afb01)

Можно подумать и о других разбиениях. Но нужно понимать, что это два разных сервиса, которые, потенциально, будут со своими задачами, жизненными циклами и тп. Поэтому класть все яйца в одну корзину не стоит. Нужно, чтобы у каждого сервиса были ровно те данные, что нужны для его работы. Не более.

2024-03-04 19:49 UTC, SHvatov commented
> Во-вторых, в вузе сегодня рассказывали, в частности, про прелести DTO: что работа с моделями "сразу из БД" сильно связывает нам руки (может, внутри приложения нам нужно какое-то поле, которое не нужно сохранять в БД) (или если оно не нужно сейчас, потом будет тяжело это править). Формулировка, была, конечно не такая, но я поняла это так. Вот и подумала: может, тут тоже сделать ДТО для сущностей чата и ссылки, и перемапливать их каждый раз из БД?

Смотри, тут некоторые ограничения накладывает тот же гибернейт, с которым вы будете работать чуть позже. Вообще, опыт показывает, что когда как) Да, ДТОхи штука классная, особенно нужная при взаимодействии с внешними системами (как с теми, что делают запросы к твоему АПИ, так и с теми, к которым запросы шлешь уже ты). Но все покрывать ДТОхами тоже не стоит. Стоит это делать по мере необходимости, ведь это, в том числе, затраты на маппинг (время) + затраты по памяти (два объекта вместо одного до тех пор, пока сессия не завершится). Сейчас, пока что, кейсов для маппинга их сущности в ДТО я не вижу. Если у тебя есть конкретные примеры - можешь их выписать, мы вместе посмотрим и подумаем, на сколько это целесообразно. 

> Очень нужен Ваш совет по поводу всего... Вообще, это мой первый проект такого объема, и складывается почти закономерность, что понимаю, что написала какие-то вещи не очень хорошо только в течение следующих шагов (домашек). Это ведь база?

Это норма) Вспоминаю собственные проекты, когда я все конвертил в ДТО, оборачивал в Optional и проверял на null)

2024-03-04 19:51 UTC, SHvatov commented
А теперь перейдем к ревью...

2024-03-05 14:09 UTC, SHvatov requested changes
@belikoooova 👍 за рефакторинг, оставил комментарии, посмотри их, пожалуйста.

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/ClientConfig.java
> +        @Value("${scrapper.base.url:localhost:8080}") String scrapperBaseUrl
Такие дефолтные значения лучше держать на уровне конфига. Часто, для разработки, их вообще уносят в local.env файлы и используют вот такой плагин для запуска локально - https://plugins.jetbrains.com/plugin/7861-envfile. Еще один довод в пользу - так легко забыть прописать значение в конфиге, а потом на проде словить ошибки из-за того, что сервис посылает запросы на локалку.

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/controller/UpdateLinkController.java
> +    private static final String MEDIA_TYPE = "application/json";
1. в Spring'е для этого уже есть константа, см. MediaType
2. а точно у тебя метод продьюсит JSON?

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/entity/dto/AddLinkRequest.java
> +@NoArgsConstructor
`@Data`, а сами поля можно сделать финальными - DTO же иммутабельны.

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/entity/link/Link.java
> +@Data
https://habr.com/ru/companies/haulmont/articles/564682/, но вообще на практике не встречал таких жестких кеков с этой связкой.

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/exception/ApiErrorResponseException.java
> +    @NotNull private final ApiErrorResponse apiErrorResponse;
Анноташка уехала(

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/exception/NoSuchChatException.java
> +public class NoSuchChatException extends RuntimeException {
Предложение - отнаследоваться от `ApiErrorResponseException`, и при создании исключения создавать `ApiErrorResponse`, как это сделано в  `ApiExceptionHandler`. Тогда хэндлер сокращается до обработки ApiErrorResponseExceptionи получения ApiErrorResponse из него, а каждое исключение само решает, какой код ответа / сообщение для пользователя отдавать в АПИ.

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/ApiExceptionHandler.java
> +    private static final String BAD_REQUEST_CODE = "400";
Лучше использовать предефайнд константы, к примеру `HttpStatus.*`

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/client/ScrapperClient.java
> +    private static final int TIMEOUT = 5;
В идеале вынести бы в конфигурацию. И хорошо бы в названии указать единицы измерения. А то ждать пять попугаев как-то не прельщает.

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/client/ScrapperClient.java
> +                status -> HttpStatus.BAD_REQUEST.equals(status) || HttpStatus.NOT_FOUND.equals(status),
Может быть маппить все 4xx и 500-ки?

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/client/ScrapperClient.java
> +                status -> HttpStatus.BAD_REQUEST.equals(status) || HttpStatus.NOT_FOUND.equals(status),
А то клиент придется дорабатывать каждый раз, когда в АПИ будет добавляться новый статус.

2024-03-05 14:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/processor/LinkUpdateProcessor.java
> +                throw new NoSuchChatException(chatId);
А это единственная причина возникновения 400 ошибки? А если будут еще?

2024-03-05 14:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/controller/ChatController.java
> +    public ResponseEntity<String> registerChat(@PathVariable Long id) {
Вот тут можно добавить валидацию на ИД чата.

2024-03-05 14:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/controller/LinkController.java
> +    ResponseEntity<ListLinkResponse> getAllLinks(@PathVariable Long chatId) {
Методы стоит сделать публичными

2024-03-05 14:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/entity/Link.java
> +    public static final Random RANDOM = new Random();
1. Точно не паблик. 
2. Лучше эту часть логики унести в стабы репозиторев - они отвечают за генерацию, не сущность.

2024-03-05 14:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/exception/ApiErrorResponseException.java
> +    @NotNull private final ApiErrorResponse apiErrorResponse;
И снова анноташка поехала не туда.

2024-03-05 14:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/exception/LinkAlreadyTracksException.java
> +public class LinkAlreadyTracksException extends RuntimeException {
Открывайте окна, сейчас будет душно. `tracks` значит, что линка кого-то отслеживает) `LinkIsAlreadyTrackedException` - вот теперь кто-то отслеживает линку.

2024-03-05 14:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/exception/NoSuchChatException.java
> +public class NoSuchChatException extends RuntimeException {
Много ошибок типа `NoSuch...`. Как насчет унификации - `NoSuchResource`?

2024-03-05 14:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/link/LinkService.java
> +        if (linkRepository.findByUrl(request.getUrl()).isEmpty()) {
```java
var link = linkRepository.findByUrl(request.getUrl())
            .orElseGet(() -> linkRepository.save(new Link(request.getUrl())));
```

2024-03-05 14:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/link/LinkService.java
> +            link = linkRepository.findByUrl(request.getUrl()).get();
Вот так делать не стоит - лишний запрос, когда сущность у тебя уже есть на руках.

2024-03-06 09:48 UTC, belikoooova commented
> Это замечательно, и, можно сказать, happens all the time) На будущее советую ознакомиться с трудами Роберта Мартина (Чистый код, Чистая архитектура - он тот еще чистюля), а также советую почитать Фаулера - Рефакторинг. Книги, конечно, немного холиварные, но для начала пойдет.

да, они уже давненько лежат в рид-листе) я ~~обязательно переживу этот март и~~ наконец-то почитаю!

2024-03-06 09:50 UTC, belikoooova commented
> В идеале такой рефакторинг стоит проводить отдельно от реализации бизнес-логики - гораздо легче понять, что поменялось и на что стоит смотреть. А так просто скоуп расширяется, и за всем ревьюверу уследить становится сложно. Вообще идеально, когда это серия мелких МРов с описанием что изменилось и зачем.

Классно! Подумаю, как можно внедрять)

2024-03-06 09:52 UTC, belikoooova commented
> Есть золотое правило - один сервис, одна БД.

> нормально, когда код дублируется (в том числе и таблицы).

Эти два факта сейчас очень меня обрадовали) Кажется, с этим куда проще жить)

2024-03-06 09:57 UTC, belikoooova commented
> Стоит это делать по мере необходимости, ведь это, в том числе, затраты на маппинг (время) + затраты по памяти (два объекта вместо одного до тех пор, пока сессия не завершится).

Это очень хорошее замечание. Я вчера наконец дописала вузовскую апишку, в целом, понятие ДТО стало более понятным) И стало понятно, почему всякие response и request - это именно ДТО. 

> Если у тебя есть конкретные примеры - можешь их выписать, мы вместе посмотрим и подумаем, на сколько это целесообразно.

Да, сейчас вернусь в коду и буду думать. Очень классно каждую неделю возвращаться к коду с новыми знаниями (скорее даже умениями и навыками, полученными на стороне)

2024-03-06 10:15 UTC, belikoooova commented
> А теперь перейдем к ревью...

Спасибо вам большое!! Очень-очень классно и ценно получать от вас такие лонгриды в ответ!

2024-03-07 12:12 UTC, belikoooova commented on scrapper/src/main/java/edu/java/scrapper/controller/ChatController.java
> +    public ResponseEntity<String> registerChat(@PathVariable Long id) {
она ведь внутри сервиса, почему лучше вынести на уровень контроллера?

2024-03-07 12:31 UTC, belikoooova commented on bot/src/main/java/edu/java/bot/exception/NoSuchChatException.java
> +public class NoSuchChatException extends RuntimeException {
💀

2024-03-07 12:53 UTC, belikoooova commented on bot/src/main/java/edu/java/bot/exception/NoSuchChatException.java
> +public class NoSuchChatException extends RuntimeException {
В ApiErrorResponseException поле ApiErrorResponse помечено финальным (как будто это логично) => для него есть конструктор => его нужно переопределить в наследнике => при каждом создании наследника нужно передавать в его конструктор экземпляр ApiErrorResponse => каждый раз при выбросе исключения создавать его, а это довольно массивная штука. Мне кажется стоит оставить это в ApiExceptionHandler, чтобы это не засоряло другой сторонний код, вот.

Есть решение, передавать в конструктор непроинициализироанный ApiErrorResponse и инициализировать его в конструкторе исключения (и всякие константы тоже хранить в самом исключении, но как будто немножко костыльное

2024-03-07 12:56 UTC, belikoooova commented on bot/src/main/java/edu/java/bot/service/processor/LinkUpdateProcessor.java
> +                throw new NoSuchChatException(chatId);
справедливо

2024-03-07 13:03 UTC, belikoooova commented on scrapper/src/main/java/edu/java/scrapper/exception/NoSuchChatException.java
> +public class NoSuchChatException extends RuntimeException {
Так ли уж много? Кажется, всего 2: для чатов и для ссылок. Кажется, сложнее будет унифицировать потом их сообщения, нежели оставить просто 2🥺

2024-03-07 13:05 UTC, belikoooova commented on bot/src/main/java/edu/java/bot/exception/NoSuchChatException.java
> +public class NoSuchChatException extends RuntimeException {
В боте, кстати, вообще это исключение убрала, но замечания выше для скрэппера вроде актуальны

2024-03-07 13:14 UTC, belikoooova commented
Таааак, вроде все.
Насчет бд и сущностей все зафиксила следующим образом:
- в боте хранятся только чаты со стейтами
- в скрэппере - ссылки и чаты со ссылками. 

Остальные замечания тоже подправила!

2024-03-08 18:08 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/controller/ChatController.java
> +    public ResponseEntity<String> registerChat(@PathVariable Long id) {
Такое поведение называется fail-fast. Чем раньше упадем, тем лучше, причём на уровне контроллера можно кастомизировать ошибку, а в сервиса ошибка будет единой для всех.

2024-03-08 18:09 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/exception/NoSuchChatException.java
> +public class NoSuchChatException extends RuntimeException {
Оки доки, если видится, что ок, то давай оставим. А там поглядим)

2024-03-11 20:11 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/exception/NoSuchChatException.java
> +public class NoSuchChatException extends RuntimeException {
> нужно передавать в его конструктор экземпляр ApiErrorResponse

Необязательно же - можно передавать только статус + сообщение, а конструировать либо по ходу пьесы, либо в конструкторе базового класса.

2024-03-11 20:12 UTC, SHvatov approved these changes
@belikoooova 👌, но насчет исключений на досуге подумай)

2024-03-11 20:19 UTC, merged